<a href="https://colab.research.google.com/github/sankalp7500/Python_coding_end_to_end/blob/main/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Creating numpy Arrays

In [2]:
# creating 1-D numpy array
a = np.array([20,24,28,32, 36, 40])
a

array([20, 24, 28, 32, 36, 40])

In [4]:
# creating 1-D numpy array from a list
a_tp = [20,24,28,32, 36, 40]
b = np.array(a_tp)
b

array([20, 24, 28, 32, 36, 40])

In [5]:
#creating 2-D numpy array
a = np.array([(1,2.5,5),(2,7.8,4)])
a

array([[1. , 2.5, 5. ],
       [2. , 7.8, 4. ]])

In [6]:
#creating 3-D numpy array
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Slicing

In [8]:
a[:]

array([[1. , 2.5, 5. ],
       [2. , 7.8, 4. ]])

In [14]:
a[0,1:3]

array([2.5, 5. ])